/**
 * Alert.java
 * This class represents the alert collection in the Firestore.
 * @author Ilea Robert-Ioan
 */
package org.example.springproject.entity;

import com.google.cloud.Timestamp;

import java.util.Map;

/**
 * This class is the representation of an alert generated by a sensor in a specific room.
 */
public class Alert {

    /**
     * The ID of the room where the alert was generated.
     */
    private String roomId;

    /**
     * The ID of the sensor that generated the alert.
     */
    private String sensorId;

    /**
     * The timestamp when the alert was generated.
     */
    private Timestamp timestamp;

    /**
     * The type of sensor that generated the alert.
     */
    private String sensorType;

    /**
     * The data associated with the alert.
     */
    private Map<String,Float> data;

    /**
     * A message describing the alert.
     */
    private String message;

    /**
     * Default constructor for the Alert class.
     * Initializes an empty alert.
     */
    public Alert() {}

    /**
     * Constructs an Alert with the specified parameters.
     * @param roomId The ID of the room where the alert was generated.
     * @param sensorId The ID of the sensor that generated the alert.
     * @param timestamp The timestamp when the alert was generated.
     * @param sensorType The type of sensor that generated the alert.
     * @param data The data associated with the alert.
     * @param message A message describing the alert.
     */
    public Alert(String roomId, String sensorId, Timestamp timestamp,String sensorType, Map<String,Float> data, String message) {
        this.roomId = roomId;
        this.sensorId = sensorId;
        this.timestamp = timestamp;
        this.sensorType = sensorType;
        this.data = data;
        this.message = message;
    }

    /**
     * Gets the room ID.
     * @return The ID of the room.
     */
    public String getRoomId() {
        return roomId;
    }

    /**
     * Sets the room ID.
     * @param roomId The ID of the room.
     */
    public void setRoomId(String roomId) {
        this.roomId = roomId;
    }

    /**
     * Gets the sensor ID.
     * @return The ID of the sensor.
     */
    public String getSensorId() {
        return sensorId;
    }

    /**
     * Sets the sensor ID.
     * @param sensorId The ID of the sensor.
     */
    public void setSensorId(String sensorId) {
        this.sensorId = sensorId;
    }

    /**
     * Gets the timestamp of the alert.
     * @return The timestamp when the alert was generated.
     */
    public Timestamp getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp of the alert.
     * @param timestamp The timestamp when the alert was generated.
     */
    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Gets the type of sensor that generated the alert.
     * @return The type of sensor.
     */
    public String getSensorType() {
        return sensorType;
    }

    /**
     * Sets the type of sensor that generated the alert.
     * @param sensorType The type of sensor.
     */
    public void setSensorType(String sensorType) {
        this.sensorType = sensorType;
    }

    /**
     * Gets the data associated with the alert.
     * @return A map containing the data of the alert.
     */
    public Map<String, Float> getData() {
        return data;
    }

    /**
     * Sets the data associated with the alert.
     * @param data A map containing the data of the alert.
     */
    public void setData(Map<String, Float> data) {
        this.data = data;
    }

    /**
     * Gets the message describing the alert.
     * @return The message of the alert.
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the message describing the alert.
     * @param message The message of the alert.
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Returns a string representation of the Alert object.
     * @return A string containing the details of the alert.
     */
    @Override
    public String toString() {
        return "Alerts{" +
                "roomId='" + roomId + '\'' +
                ", sensorId='" + sensorId + '\'' +
                ", timestamp=" + timestamp +
                ", data=" + data +
                ", message='" + message + '\'' +
                '}';
    }
}
